# Dependencies
markdown:         redcarpet
highlighter:      pygments
encoding: utf-8

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            floede
tagline:          'A dev blog'
description:      'A diary and documentation of my experiences learning Ruby on Rails. Made by <a href="https://twitter.com/floede" target="_blank">@floede</a>.'
url:              http://www.floede.dk
baseurl:          /

author:
  name:           'Janus Hasseriis'
  url:            https://twitter.com/floede

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/floede

# Github pages settings
safe: true
lsi: false